# Generated by Django 5.0.6 on 2024-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_delete_estadocita_alter_pdf_estado_cita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='estado',
            field=models.BooleanField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default=False),
        ),
    ]
