# Generated by Django 5.0.6 on 2024-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Aceptado'), (False, 'Rechazado')], default=False),
        ),
    ]
