# Generated by Django 5.0.6 on 2024-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_alter_pdf_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Aceptado'), (False, 'Rechazado')], default=False),
        ),
    ]
