# Generated by Django 5.0.6 on 2024-05-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0006_alter_cita_estado'),
        ('Registro', '0006_alter_trabajador_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField()),
                ('fecha_atencion', models.DateField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='Citas.cita')),
                ('doctor_atendiendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
