# Generated by Django 5.0.6 on 2024-05-14 03:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0007_atencioncita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencioncita',
            name='fecha_atencion',
        ),
        migrations.RemoveField(
            model_name='atencioncita',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='atencioncita',
            name='observacion_Analisis',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Análisis'),
        ),
        migrations.AddField(
            model_name='atencioncita',
            name='observacion_Objetiva',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Objetiva'),
        ),
        migrations.AddField(
            model_name='atencioncita',
            name='observacion_Plan',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='atencioncita',
            name='observacion_Subjetiva',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Subjetiva'),
        ),
        migrations.AlterField(
            model_name='atencioncita',
            name='cita',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='Citas.cita'),
        ),
    ]
