# Generated by Django 5.0.6 on 2024-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0008_remove_atencioncita_fecha_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencioncita',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Cita Atendida'), (False, 'Cita no atendida')], default=False),
        ),
    ]
