# Generated by Django 5.0.6 on 2024-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0009_atencioncita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombre',
            field=models.CharField(default='Cita', max_length=50),
        ),
    ]
