# Generated by Django 5.0.6 on 2024-05-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0010_cita_nombre'),
        ('Registro', '0006_alter_trabajador_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('doctor_atendiendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_atendidas', to='Registro.doctor')),
                ('proxima_cita', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_cita', to='Citas.cita')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
