# Generated by Django 5.0.6 on 2024-05-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0011_urlcita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcita',
            name='doctor_atendiendo',
        ),
        migrations.AlterField(
            model_name='urlcita',
            name='proxima_cita',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_cita', to='Citas.cita', verbose_name='Cita url'),
        ),
    ]
