# Generated by Django 5.0.6 on 2024-05-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0012_remove_urlcita_doctor_atendiendo_and_more'),
        ('Registro', '0006_alter_trabajador_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.trabajador'),
        ),
    ]
