# Generated by Django 5.0.4 on 2024-05-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_municipios',
            name='fk_cat_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalago.cat_estados', verbose_name='Estado'),
        ),
    ]
